services:
  backend:
    build: ./Backend
    container_name: zomoro-be
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: zomoro-fe
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped